language: node_js
cache:
  directories:
    - ~/.npm
script:
  - yarn build
  - yarn test-travis
notifications:
  email: false
node_js:
  - "10"
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
after_success:
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
